/**
 * TuitionBoard AI - Export Service
 * Exports blackboard snapshots as PNG images and full structured lesson notes as Markdown.
 */

class ExportService {
  constructor() {}

  /**
   * Export the visual chalkboard (background + formulas + freehand drawings) as a PNG image
   */
  async exportBoardImage() {
    const container = document.getElementById("chalkboardContainer");
    const drawingCanvas = document.getElementById("drawingCanvas");
    if (!container || !drawingCanvas) return;

    try {
      // Create an offscreen composite canvas
      const width = container.clientWidth;
      const height = container.clientHeight;
      const dpr = 2; // High-res export

      const exportCanvas = document.createElement("canvas");
      exportCanvas.width = width * dpr;
      exportCanvas.height = height * dpr;
      const ctx = exportCanvas.getContext("2d");
      ctx.scale(dpr, dpr);

      // Fill theme background
      const theme = window.chalkboard ? window.chalkboard.currentTheme : "classic-green";
      let bgColor = "#1b382b"; // Classic green chalkboard
      if (theme === "dark-slate") bgColor = "#1e2430";
      if (theme === "whiteboard") bgColor = "#f8fafc";
      if (theme === "blueprint") bgColor = "#0f2744";

      ctx.fillStyle = bgColor;
      ctx.fillRect(0, 0, width, height);

      // Draw wood frame border
      ctx.lineWidth = 8;
      ctx.strokeStyle = "#854d0e"; // Wood border
      ctx.strokeRect(4, 4, width - 8, height - 8);

      // Draw title banner
      const topicTitle = window.appState && window.appState.currentLesson ? window.appState.currentLesson.title : "Tuition Board Notes";
      ctx.fillStyle = theme === "whiteboard" ? "#0f172a" : "#f5f5f0";
      ctx.font = "bold 20px 'Plus Jakarta Sans', sans-serif";
      ctx.fillText(topicTitle, 24, 36);

      // Stamp date and branding
      ctx.font = "12px 'Plus Jakarta Sans', sans-serif";
      ctx.fillStyle = theme === "whiteboard" ? "#64748b" : "#94a3b8";
      ctx.fillText(`TuitionBoard AI - ${new Date().toLocaleDateString()}`, 24, 56);

      // Composite the drawing canvas
      ctx.drawImage(drawingCanvas, 0, 0, width, height);

      // Trigger download
      const dataUrl = exportCanvas.toDataURL("image/png");
      const a = document.createElement("a");
      a.href = dataUrl;
      a.download = `tuition-board-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);

      if (window.soundEffects) window.soundEffects.playSuccessChime();
    } catch (err) {
      console.warn("Export image failed:", err);
    }
  }

  /**
   * Export the entire 5-stage lesson as formatted Markdown
   */
  exportLessonMarkdown() {
    if (!window.appState || !window.appState.currentLesson) return;
    const lesson = window.appState.currentLesson;

    let md = `# 🎓 ${lesson.title}\n`;
    md += `**Subject:** ${lesson.subject} | **Grade Level:** ${lesson.gradeLevel}\n`;
    md += `*${lesson.tagline}*\n\n---\n\n`;

    lesson.stages.forEach(stage => {
      md += `## Stage ${stage.stageNumber}: ${stage.title}\n\n`;
      md += `> **👨‍🏫 Tutor Explanation:**\n> ${stage.tutorDialogue}\n\n`;

      stage.boardItems.forEach(item => {
        if (item.type === "title") {
          md += `### ${item.content}\n\n`;
        } else if (item.type === "analogy") {
          md += `💡 **Analogy (${item.title || 'Tuition Analogy'}):**\n${item.content}\n\n`;
        } else if (item.type === "latex") {
          md += `${item.label ? `**${item.label}**\n` : ''}$$\n${item.formula}\n$$\n\n`;
        } else if (item.type === "stepList") {
          item.steps.forEach(step => {
            md += `${step.stepNum}. **${step.desc}**\n   $$\n   ${step.latex || ''}\n   $$\n`;
          });
          md += "\n";
        } else if (item.type === "chalkNote") {
          md += `📌 *Teacher Note:* ${item.text}\n\n`;
        } else if (item.type === "quiz") {
          md += `🎯 **Checkpoint Question:** ${item.question}\n`;
          item.options.forEach((opt, idx) => {
            md += `  - [${idx === item.correctIndex ? 'x' : ' '}] ${String.fromCharCode(65 + idx)}) ${opt}\n`;
          });
          md += `\n*Explanation:* ${item.explanation}\n\n`;
        }
      });
      md += `---\n\n`;
    });

    md += `\n*Generated by TuitionBoard AI - Interactive Classroom Blackboard*\n`;

    // Trigger download
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${lesson.id || 'tuition-lesson'}-notes.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    if (window.soundEffects) window.soundEffects.playSuccessChime();
  }
}

window.exportService = new ExportService();
